"#version 330 core\n"
"in vec3 fPosition;\n"
"in vec3 fNormal;\n"
"in vec2 fTexCoord;\n"
"out vec4 color;\n"
"\n"
"struct DirectionalLight {\n"
"    vec3 direction;\n"
"    vec3 color;\n"
"    float intensity;\n"
"};\n"
"\n"
"struct Material {\n"
"    vec3 kds[2];\n"
"    float blend;\n"
"};\n"
"\n"
"uniform Material material;\n"
"uniform DirectionalLight light;\n"
"uniform sampler2D mapKds[2];\n"
"\n"
"\n"
"void main() {\n"
"    vec3 normal = normalize(fNormal);\n"
"    vec3 lightDir = normalize(-light.direction);\n"
"\n"
"    float lambert = max(dot(normal, lightDir), 0.0f);\n"
"    \n"
"    vec4 texColor0 = texture(mapKds[0], fTexCoord) * vec4(material.kds[0], 1.0f);\n"
"    vec4 texColor1 = texture(mapKds[1], fTexCoord) * vec4(material.kds[1], 1.0f);\n"
"    vec4 texColor = mix(texColor0, texColor1, material.blend);\n"
"\n"
"    color = texColor * vec4(light.color, 1.0f) * light.intensity * lambert;\n"
"\n"
"};\n"