"#version 330 core\n"
"in vec2 fTexCoord;\n"
"out vec4 color;\n"
"\n"
"struct Material {\n"
"    vec3 colors[2];\n"
"    int repeat;\n"
"};\n"
"\n"
"uniform Material material;\n"
"\n"
"void main() {\n"
"    vec2 uv = fTexCoord * material.repeat;\n"
"    float checker = mod(floor(uv.x) + floor(uv.y), 2.0);\n"
"    color = vec4(checker < 0.5 ? material.colors[0] : material.colors[1], 1.0);\n"
"};\n"